"""
Django settings for privacy_compare project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from the environment so a real key never has to live in source
# control. The fallback below is a throwaway value, valid for local
# development only — any real deployment (Vercel included) must set
# DJANGO_SECRET_KEY as an actual environment variable with its own
# generated key. See .env.example.
_DEV_SECRET_KEY = "django-insecure-dev-only-ubry1^t+3%*_eoa5p-a-g&+y^hi56=+2i115z6^=po!^7phwdp"
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", _DEV_SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# This repo is public, so the fallback key above is public too. Refuse to
# boot a non-debug deployment that forgot to set its own.
if not DEBUG and SECRET_KEY == _DEV_SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is False. "
        "See .env.example for how to generate one."
    )

ALLOWED_HOSTS = [
    h.strip() for h in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if h.strip()
]

# Vercel sets these at runtime — VERCEL_URL to the *current deployment's*
# unique hostname (a new one every deploy), VERCEL_PROJECT_PRODUCTION_URL
# to the stable production alias. Neither is known in advance, so they
# can't just go in DJANGO_ALLOWED_HOSTS — trust both automatically when
# present. A custom domain still needs to be added via DJANGO_ALLOWED_HOSTS.
_vercel_hosts = [
    h
    for h in (
        os.environ.get("VERCEL_URL"),
        os.environ.get("VERCEL_PROJECT_PRODUCTION_URL"),
    )
    if h
]
if _vercel_hosts:
    ALLOWED_HOSTS.extend(_vercel_hosts)
    CSRF_TRUSTED_ORIGINS = [f"https://{h}" for h in _vercel_hosts]
else:
    CSRF_TRUSTED_ORIGINS = [
        o.strip()
        for o in os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
        if o.strip()
    ]

# Vercel terminates TLS at the edge and forwards requests to the app over
# plain HTTP with this header set — without it Django can't tell the
# request was actually HTTPS, which breaks CSRF and secure-cookie checks.
if os.environ.get("VERCEL"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Production hardening, driven by `manage.py check --deploy`.
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 365  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "comparison",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Serves static files directly from the app process. Vercel's
    # serverless functions have no separate static file server and no
    # persistent disk to run `collectstatic` into ahead of time, so
    # WhiteNoise (with WHITENOISE_USE_FINDERS below) serves them straight
    # from the app/admin source directories on every request.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "privacy_compare.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "privacy_compare.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SQLite locally (zero setup, matches the README's local-dev instructions).
# In production — Vercel's serverless functions have no persistent disk,
# so a SQLite file wouldn't survive between requests — set DATABASE_URL
# (Vercel's Postgres/Neon integration injects POSTGRES_URL automatically;
# either name is read here) to switch to Postgres with no code changes.
_database_url = os.environ.get("DATABASE_URL") or os.environ.get("POSTGRES_URL")

if _database_url:
    DATABASES = {"default": dj_database_url.parse(_database_url, conn_max_age=600)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}
# Serve straight from each app's static/ directory (this project's own
# comparison/static plus the admin's) instead of requiring a collectstatic
# build step — there's no Vercel build hook wired up to run one, and the
# static payload is one CSS file and one JS file plus the admin's.
WHITENOISE_USE_FINDERS = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
