# Generated by Django 5.2.17 on 2026-09-01 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=170, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="One or two sentences explaining what this category compares.",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Optional emoji used as a lightweight icon in the UI, e.g. '🌍'.",
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Law",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code used in badges/tables, e.g. LGPD, GDPR, CCPA/CPRA.",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Official full name of the law, e.g. 'Lei Geral de Proteção de Dados Pessoais (Lei nº 13.709/2018)'.",
                        max_length=255,
                    ),
                ),
                (
                    "jurisdiction",
                    models.CharField(
                        help_text="e.g. Brazil, European Union / EEA, California (USA).",
                        max_length=100,
                    ),
                ),
                (
                    "regulator",
                    models.CharField(
                        blank=True,
                        help_text="Primary enforcement authority, e.g. 'ANPD', 'National Data Protection Authorities', 'CPPA / CA Attorney General'.",
                        max_length=255,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True,
                        help_text="Date the law (or its main enforcement provisions) took effect.",
                        null=True,
                    ),
                ),
                (
                    "official_source_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the official statutory text (e.g. planalto.gov.br, eur-lex.europa.eu, oag.ca.gov).",
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(
                        default="#334155",
                        help_text="Accent color used for this law's badge/column in the UI.",
                        max_length=7,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Display order across the site (e.g. LGPD, GDPR, CCPA/CPRA).",
                    ),
                ),
            ],
            options={
                "verbose_name": "Law",
                "verbose_name_plural": "Laws",
                "ordering": ["order", "code"],
            },
        ),
        migrations.CreateModel(
            name="ScenarioQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flag",
                    models.SlugField(
                        help_text="Internal identifier referenced by scenario rules, e.g. 'process_eu_data'.",
                        unique=True,
                    ),
                ),
                ("question_text", models.CharField(max_length=300)),
                ("help_text", models.CharField(blank=True, max_length=300)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ComparisonEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        help_text="Short one-line takeaway shown in the comparison table/cards.",
                        max_length=300,
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Longer explanation shown when the entry is expanded.",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the specific primary-source provision backing this entry, if verified.",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Check only after this entry has been personally verified against the official statutory text.",
                    ),
                ),
                (
                    "verification_notes",
                    models.TextField(
                        blank=True,
                        help_text="TODO/verification notes, e.g. 'TODO: VERIFY against official source (planalto.gov.br) before publishing.'",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="comparison.category",
                    ),
                ),
                (
                    "law",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="comparison.law",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Comparison entries",
                "ordering": ["category__order", "law__order"],
                "unique_together": {("category", "law")},
            },
        ),
        migrations.CreateModel(
            name="ScenarioRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "required_for_all",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, this question is part of an AND group: the law is only triggered if every 'required_for_all' rule for it is answered Yes. If unchecked, this question alone (OR) is enough to trigger the law.",
                    ),
                ),
                (
                    "law",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenario_rules",
                        to="comparison.law",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="comparison.scenarioquestion",
                    ),
                ),
            ],
            options={
                "unique_together": {("law", "question")},
            },
        ),
    ]
