# Generated by Django 5.2.17 on 2026-09-27 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comparison", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ("order", "name"), "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="comparisonentry",
            options={
                "ordering": ("category__order", "law__order"),
                "verbose_name_plural": "Comparison entries",
            },
        ),
        migrations.AlterModelOptions(
            name="law",
            options={
                "ordering": ("order", "code"),
                "verbose_name": "Law",
                "verbose_name_plural": "Laws",
            },
        ),
        migrations.AlterModelOptions(
            name="scenarioquestion",
            options={"ordering": ("order", "id")},
        ),
    ]
