# Generated by Django 5.2.17 on 2026-09-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comparison", "0002_use_tuple_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comparisonentry",
            name="summary",
            field=models.CharField(
                help_text="One- or two-sentence takeaway shown in the comparison table/cards.",
                max_length=600,
            ),
        ),
    ]
